[package]
name = "support"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_cmd = "1.0.2"
predicates = "1.0.7"
pretty_assertions = "0.7.2"
scopeguard = "1.1.0"
