pub mod explicate_control;
pub mod instruction_selection;
pub mod interference;
pub mod liveness_analysis;
pub mod merge_blocks;
pub mod patch_instructions;
mod remove_complex_operands;
pub mod shrink;
pub mod typecheck;
pub mod uniquify;
pub mod move_biasing;
pub mod register_allocation;