[package]
name = "ast"
version = "0.1.0"
edition = "2018"

[dependencies]
id-arena = "2.2.1"
indexmap = "1.8.1"
pretty = "0.11.3"
support = { path = "../support" }

[dev-dependencies]
pretty_assertions = "1.2.1"
